### ISSUE TITLE
Remove README from gitignore and added profiles.ini

### ISSUE THREAD

**Issue by giacomocerquone** [KurtisLiggett/Simple-IP-Config#11]
Readme file shouldn't be ignored by git and profiles.ini is needed in order to test the application without causing the repo to change!

**Comment by giacomocerquone** [comment]
Before you close the PR, I'd consider to exclude main_stripped too... why there is an all in one file that keeps my editor crashing? 😆

**Comment by KurtisLiggett** [comment]
main_stripped is a product of using `#AutoIt3Wrapper_Run_Au3Stripper=y`.
It strips out unused functions and variables and greatly reduced the size of the exe. I can then use the file for reference if someone gets an error with a line number.

We can exclude it from the repo though since it is not really a source file. It just got mixed in when I uploaded all of my files.

**Comment by giacomocerquone** [comment]
Since you merged, is better to not open a new PR! Just add main stripped to the gitignore ;)
