### ISSUE TITLE
Firefox reports Malware present [BUG] 

### ISSUE THREAD

**Issue by wakkoroti** [KurtisLiggett/Simple-IP-Config#152]
**Version:**
2.9.4

Firefox reports that portable version (zip file) has malware present.

**Comment by wakkoroti** [comment]
Same with install version
![ipconfigsnap01](https://user-images.githubusercontent.com/67204527/170737708-fa9149a7-31cc-40b9-89b3-4fbdddad902d.png)
.

**Comment by blackcrack** [comment]
this can not be, Kurtis software iss okey, please check the wrong positive report at Microsoft, 
the fail is by Microsoft, or want MS to be this freeware goes done.. so, it's not infected..
So please, go to MS and report this false positive, thank you :)

**Comment by KurtisLiggett** [comment]
@blackcrack is correct, the files are not infected. This is something that happens sometimes when antivirus companies get lazy and make a blanket rule for the whole programming language and not the software.
The only way to fix it is to report it to Firefox or whatever antivirus it is using.

**Comment by blackcrack** [comment]
@KurtisLiggett Take please a look, maybe could you Report it :  
https://www.google.com/search?q=Microsoft+Report+Malware+Wrong+positive

best and *wave* :wave:

**Comment by KurtisLiggett** [comment]
My antivirus ended up finally killing my exe as well.. so v2.9.5 is released and so far is not being flagged.

**Comment by ww4** [comment]
v2.9.5 is being reported as malware as well, Chrome Safe Browsing and Microsoft Defender have blocked it. They link to this: https://go.microsoft.com/fwlink/?linkid=142185&name=Trojan:Win32/Wacatac.B!ml&threatid=2147735505

I find it slightly concerning that this is being flagged over and over by different antiviruses. Are we sure there's nothing going on?

**Comment by HansieNL** [comment]
Kaspersky Internet Security removed the Simple IP Config 2.9.5.exe with the message it contains HackTool.Win32.GameHack.cfzx.

**Comment by KurtisLiggett** [comment]
Made some attempts at resolving this. Uploading test file here, to see if Firefox blocks it again.
[Simple IP Config 2.9.6.exe.zip](https://github.com/KurtisLiggett/Simple-IP-Config/files/8857943/Simple.IP.Config.2.9.6.exe.zip)

**Comment by KurtisLiggett** [comment]
On my PC, if I try downloading the latest release v2.9.5, Firefox detects it as a virus.
If I download the 2.9.6 zip in the post above, it does NOT detect. I would appreciate it if anyone else is willing to try the test and report back.

**Comment by blackcrack** [comment]
hmm.. it was at my Firefox not.., but the downloadbloack of firefox if in anyway really bad, because it is not a virus dedectore, it's a blacklist.. if you look on "about:config", is there a "warning" accept the risk and press the button.
If you now type in on the textline under the Adressline "blocking" do you see webadresses where be recive blockinglists, where be from Mozilla adresses and blocked download if files, this have nothing to do with Virusfiles and something, this have more to do with blacklisting of files where should the user not download.. and i bet, ms and other factorys have the fingers on it..  

I have adjust this settings, because nobady say's me what is "save" and what is okey, because if i am be on the way in the net, should i know, what's okey and what's not.. because if any one say "this is okey for you" can he also steer, what i am downloading and what's not and i want not be steering by an foreigner/stranger .. this can not be.. because then can he also say, which way i have to walk.. and i be foreigner steered .

this have nothing to do with a free will.. Firefox becomes more and more bad.. imho.. also in commercial sense ..
it be files blocked every more where be really free..

best
Blacky

![grafik](https://user-images.githubusercontent.com/7925717/172526792-0d1e03ac-84a1-499d-a7b4-fc6b47d57645.png)

**Comment by KurtisLiggett** [comment]
I agree with all of your comments about Firefox!

But my antivirus Sentinel One even detected it.

**Comment by JonnyTech** [comment]
@KurtisLiggett FYI:

![download](https://user-images.githubusercontent.com/3584732/172547526-5b27b035-e801-4c40-8d8c-26312caea4c9.png)

Good job! Cheers.

**Comment by GISED-Link** [comment]
I have used windows powershell to donwload the file and it works. But there are things I can't understand:

- Why the download page of your website is redirecting to Sourceforge instead of Github?
- Why version 2.8 on Sourceforge is downloading nicely and not this versions?
- Are you still using HackTool.Win32.GameHack.cfzx for your newer version 2.9.6?

**Comment by KurtisLiggett** [comment]
Everyone, finally an official release to address these antivirus issues once and for all. Please report back!
### [v2.9.6.1](https://github.com/KurtisLiggett/Simple-IP-Config/releases/tag/2.9.6.1)

**Comment by Testato** [comment]
No it's not solved 😅
https://github.com/KurtisLiggett/Simple-IP-Config/issues/156
I opened a new Issue because it is not related to Firefox

**Comment by KurtisLiggett** [comment]
@Testato back to the drawing board I guess..

**Comment by KurtisLiggett** [comment]
It seems I may have to submit individually to each antivirus company.  Closing this since Firefox is no longer detecting malware.
If anyone still has issues with Firefox, feel free to open this issue back up. For other antivirus please open a new issue.
