### ISSUE TITLE
Some ideas

### ISSUE THREAD

**Issue by leillo1975** [KurtisLiggett/Simple-IP-Config#154]
Hi
I'm working on a Technical School, and sometimes I have to install the same SO image in a lot of PCs. Then I have to change the static IP on all, and the PC name (sometimes the Workgroup/Domain). I find your tool very useful, but I think that could better for my work with this improvements:
-When you open the tool, the IP fields have a default IP. I think is better if the shown IP is the current IP on the PC. This way, in my case I only have to change the last IP number.
-It would be perfect to also be able to change the PC name and workgroup/domain elsewhere, and have it default to the current one.In this way, if I have an image with the name PC00, and I want to use it in the 10th PC in a classroom, I could easily change it to PC10.

Of course I know that these changes are very personal, but I think that many people with my same kind of work or similar, can find your awesome tool very useful.

**Comment by KurtisLiggett** [comment]
@leillo1975 Thanks for the suggestions! Hopefully the following helps.

`-When you open the tool, the IP fields have a default IP. I think is better if the shown IP is the current IP on the PC. This way, in my case I only have to change the last IP number.`

I think you have 2 good options using the program as it is now.
1. Save your first profile as the IP you want as the default. That way when you start the program, it is automatically filled in for you.
2. Open the program, then press Ctrl+P (or go to Tools->Pull from adapter) to fill the IP with the current adapter IP addresses.

`-It would be perfect to also be able to change the PC name and workgroup/domain elsewhere, and have it default to the current one.In this way, if I have an image with the name PC00, and I want to use it in the 10th PC in a classroom, I could easily change it to PC10.`

As @blackcrack mentioned, a discussion has already been created for workgroups here: #121. I haven't spent much time on this since I don't have a good PC to test this on.

**Comment by leillo1975** [comment]
Thanks for the answers, especially to the first question, and sorry for ask here and not in the discussions.
