### ISSUE TITLE
[BUG] "Domain:" text shown for workgroups

### ISSUE THREAD

**Issue by KurtisLiggett** [KurtisLiggett/Simple-IP-Config#166]
**Expected Behavior:**
When the computer belongs to a domain, the program should display "Domain: domain-name".
When the computer belongs to a workgroup, the program should display "Workgroup: workgroup-name".

**Actual Behavior:**
The program displays "Domain:" even when in a workgroup.

**Comment by blackcrack** [comment]
the Domain Name is the Last Domain name behind the fullstop of the Computer-Name

ComputerName.Domainname, because the Somainname describes if commercial or a Organisation or a land, like de, Tr,gr or an .gov, Goverment

My full domainname is from Germany, .de the name of the Server is maped on the Servernumber:
blackysgate  . de
Name . domain-name

my Homeserver over selfhost
blackysgate.net  describes my Servername maped on the DyndnsNumber from dyndns-provider
and the net is my home-net Domain-name, the Domain is a Network so, .net  or org.. or com, for commercial
and .gov for Goverment like Citizenhalloflondon.uk,gov or something.

Workgroup is mostly connected over Samba/smb/Lanman in WinNT-(service)
and setting up a group it's moustly meant a Samba-Group/WinNT Network File-System

So it's a Nameofthecomputer.domainname  something totally other as a Goup who meant a Lanman-SMB Group (Workgroup)
working group where have access to the same Filesystem in the network. (it meant Network File system SMB-Protokoll 1-4/5)

i hope it has helped :)

best

**Comment by KurtisLiggett** [comment]
This bug is just referring to the text in the lower right. When not part of a domain, it should display "Workgroup:" instead of "Domain:"

It was a simple typo I made in the last version.
![image](https://user-images.githubusercontent.com/29669372/188714948-8cf1d426-b600-4ad2-a105-dc24f00f26fb.png)

**Comment by blackcrack** [comment]
which let show the actual setted up the workgroup, but is should see the Computername.domain... i see imho..?

so, 2 different things.. yes :)

**Comment by blackcrack** [comment]
oh i see, _->_corp._<-_  computername.commercial .... (good mooorning, blacky ;) in double meaning)

**Comment by KurtisLiggett** [comment]
Now available with release v2.9.7 - [Download Here](https://github.com/KurtisLiggett/Simple-IP-Config/releases/tag/2.9.7)
