### ISSUE TITLE
starting application

### ISSUE THREAD

**Issue by zapy85** [KurtisLiggett/Simple-IP-Config#52]
Would it be possible to not start the application to the system tray if you start it and it isn't started?

**Comment by KurtisLiggett** [comment]
Have you verified that the option "Startup in the system tray" is not checked?

![image](https://user-images.githubusercontent.com/29669372/32707720-81b525b6-c7eb-11e7-8b91-964f14946a3e.png)

**Comment by zapy85** [comment]
Hi, yes that option is checked, but that, if possible, should only be the case when you do a boot.

Not if you want to start the software from desktop if you have closed it and want to start it again.

**Comment by Otiel** [comment]
Indeed that would be nice. Go in the systray when the software is started with Windows (the idea is to have the software always on hand when needed, but the user shouldn't see that the software is being started to avoid being bothered - goes with issue #46 ), and start it maximized when it is started by the user.

So maybe we'll need a command line option to set a shortcut in `shell:startup`?

**Comment by KurtisLiggett** [comment]
I would be okay with adding the command line option for starting to the tray and leaving the functionality of the checkbox in the settings window for ALWAYS starting in the tray.

**Comment by Otiel** [comment]
That seems good for me, it lets all options for the user.

**Comment by zapy85** [comment]
Just to be clear.
The current checkbox would always start it to systray, thus making the -systray command unnecessary as it already does this.
But launching the application from desktop would bring it to the front (so you still need to fix that/have a check if it is started or not)
Adding -systray to the startup-shortcut would send it to tray (why would you want to do that, then you would use the checkbox?)

What i propose:
Rename the current checkbox to " Start SimpleIP at boot "
Add a second checkbox " Always start minimized "

That's common practice, if it's possible, i don't know the limits for autoit, your proposed way might be easier/only possible way.

**Comment by KurtisLiggett** [comment]
OK, I misunderstood your original request.

I think the main confusion comes from the wording of the option "Startup in the system tray."
Maybe a better description is "Always start in system tray." There's not currently a feature to make the program start with Windows logon -- you have to add the shortcut to the startup folder yourself.

Of course, 'Start SimpleIP at boot' is a feature that could be easily added. Please start a new issue requesting that feature if you'd like.

The reason we would need the -systray parameter is because I have no way of knowing how the program was started: at boot from the startup folder or someone clicking the icon from the desktop. This would all be handled internally if the boot option was added to the program.

**Comment by zapy85** [comment]
Yeah, sorry about that @Kurtis I was way to tired to post that, read it later on and completely understood your confusion :D

**Comment by KurtisLiggett** [comment]
Closing this issue since new topics have been created.
