### ISSUE TITLE
Update Error

### ISSUE THREAD

**Issue by blackcrack** [KurtisLiggett/Simple-IP-Config#80]
![screen 00000](https://user-images.githubusercontent.com/7925717/51800315-a2b2a480-222d-11e9-9521-c0f6ad8aea47.jpg)

**Comment by Testato** [comment]
Confirmed on Win7 in version 2.9.2

**Comment by KurtisLiggett** [comment]
This is really just an informational message to let you know that the download failed.
Perhaps a message in the status bar would be better.

**Comment by blackcrack** [comment]
it's maybe better a manual [Update] Button for this
as every at any start of the program to let automatically check the update.
It's maybe meant really well, but a automatically : 
"i looking for anything outside of the  computer" 
if the configuration not fit's for looking for a update it's note really not well .
And maybe check the download-url via update button, or let pop open the the Relesepage it is maybe better and let the choice the User/Admin for open/looking for an more new software..
and at any start a error-massage it is also not a good thing .. ;)

if the program good, want the user ever check by self for a update, promiced ;)
you could maybe create a php or a textfile where you can update the releasenumber and downloadurl and the program check it.. and tell if a more higher Release on the homepage 
"New Release, this one 1.22, the new 1.24, want you [update] ? "
and if the networkc config not fit's, does nothing view and not a "error-window"
if the network config not right not a " husten i have a problem" window ;)

best regards
Blacky

**Comment by KurtisLiggett** [comment]
Check the latest version 2.9.3
Improvements:
* If new version detected, show the new dialog with a link to the latest release page. Otherwise don't show anything.
* Only show new version dialog once every 7 days OR when you manually click the check for updates button.
* If an error occurs on automatic update check, don't show any messages.
* If an error occurs when you manually click the check for updates button, show all error messages.

**Comment by Testato** [comment]
I will try it, thanks
